[env:esp32-s3-waveshare-7]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- Configuration de survie ---
board_build.arduino.memory_type = qio_opi ; Indispensable pour la PSRAM
board_build.flash_mode = dio              ; On repasse en DIO pour tester la stabilité
board_build.f_flash = 40000000L           ; On baisse la vitesse de la flash à 40MHz
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1           ; Pour voir les messages Serial via l'USB natif

lib_deps = 
    moononournation/GFX Library for Arduino @ 1.4.2